//
//  GrocerySections.swift
//  Bishop_GroceryApp
//
//  Created by Bishop,Mackenzie N on 11/17/22.
//

import Foundation
import UIKit

struct GrocerySections{
    var section = ""
    var items_Array:[GroceryItem] = []
}

struct GroceryItem{
    var itemName = ""
    var itemImage = ""
    var itemInfo = ""
}

let section1 = GrocerySections(section: "Fruits",
                               items_Array: [
                               GroceryItem(itemName: "Grapes", itemImage: "grape", itemInfo: "Treat yourself to the delicious, juicy flavor of Fresh Red Seedless Grapes. These grapes are bursting with flavor and are completely seedles. Prized for their lush, juicy pulp, very sweet flavors, and highly aromatic skins that offer a pleasant chewiness, they are also perfect for creating stunning cheese boards and charcuterie plates by pairing them with fresh cheese, crackers, or delectable meats like prosciutto. If you want to be really creative, you can freeze them and use them and ice cubes that won't melt and release water into your favorite drinks. Treat yourself to the fresh taste of Fresh Red Seedless Grapes."),
                               GroceryItem(itemName: "Strawberries", itemImage: "strawberry", itemInfo: "The sweet, juicy flavor of Fresh Strawberries make them a refreshing and delicious treat. Enjoy them for breakfast, lunch, dinner, or dessert. Use them as topping for pancakes, bake them in a mouthwatering bread, mix them with cucumbers for a light and flavorful salad, or puree them for strawberry shortcake. They contain essential vitamins and nutrients like vitamin C, fiber, potassium, vitamin B and magnesium making them perfect for a healthy diet. Prior to serving simply gently wash them, remove the leafy caps, and enjoy the fresh taste. Refrigerate the berries to keep them fresh and ready for use. Pick up Fresh Strawberries today and savor the delectable flavor."),
                               GroceryItem(itemName: "Bananas", itemImage: "banana", itemInfo: "Enjoy the sweet, tropical taste of Fresh Bananas. Bananas are a good source of several vitamins and minerals including potassium, vitamin B6 and vitamin C and are low in sodium. Enjoy them at breakfast, lunch, dessert, or anytime you want a healthy snack. Use them to make a loaf of moist banana bread and enjoy with a hot cup of coffee in the mornings or layer them with pudding and vanilla wafer cookies for a light, sweet banana pudding that's perfect for dessert. Simply peel open the banana and savor the delicious taste of this sweet fruit. Bring home Fresh Bananas and make them a part of your day."),
                               GroceryItem(itemName: "Peaches", itemImage: "peach", itemInfo: "The sweet, juicy flavor of Fresh Peaches make them a refreshing and delicious treat. Enjoy them for breakfast, lunch, dinner, or dessert. Use them as topping for pancakes, bake them in a mouthwatering bread, mix them with cucumbers for a light and flavorful salad, or puree them for peach jam. Pick up Fresh Peaches today and savor the delectable flavor."),
                               GroceryItem(itemName: "Plums", itemImage: "plum", itemInfo: "Enrich your day with some juicy plums. Fruit is a healthy snack and an important part of a healthy diet for most people. It provides fiber and essential vitamins and minerals. Black plums are no exception. They contain vitamin A and other vitamins and minerals. Each plum fruit bite is sweet and delicious. Slice one and enjoy it alone, or add it to salads and other recipes. Plums are a versatile fruit with a unique flavor and a meaty yet juicy texture. There are approximately 3-4 plums per lb. Plums, each.")
                               ]
)

let section2 = GrocerySections(section: "Vegetables",
                               items_Array: [
                               GroceryItem(itemName: "Bell Peppers", itemImage: "bell_pepper", itemInfo: "Enhance your meals with the delicious flavor of Bell Peppers. These vegetable contain essential vitamins such as A and C, and minerals including calcium and magnesium. Bell pepper, also known as green capsicum, has a crisp flavor that enhances a variety of recipes. Dice bell peppers and put them in a hearty chili, slice them and add to a deli sandwich, sautee them with onions and serve on a hoagie roll with a bratwurst, or stir-fry with thinly-sliced steak and serve with rice. A hollowed-out green bell pepper can be filled with sausage, mushrooms, and rice to create a delicious stuffed pepper that will have the family asking for seconds. Lunches and dinners are more scrumptious when fresh green peppers are part of the meal. They also taste delicious raw alongside other vegetables. Add your favorite dip for a healthy, crunchy crudite. Cooked or uncooked, Bell Peppers are an excellent item to have on hand."),
                               GroceryItem(itemName: "Carrots", itemImage: "carrot", itemInfo: "Carrots can make a versatile addition to various meals. They have a crisp crunch and a bold taste. These California carrots are easy to cut into pieces for adding to a stew, pot roast or meat pie. Slice them thin and add them to a salad with some lettuce, tomatoes, olives and other ingredients. These fresh carrots are also ideal for dipping in dressing."),
                               GroceryItem(itemName: "Cucumbers", itemImage: "cucumber", itemInfo: "Enjoy the fresh, crisp, delicious flavor of Cucumber. Packed with nutritional benefits such as being naturally low in calories, carbohydrates, sodium, fat, and cholesterol, cucumbers also provide potassium, fiber, and vitamin C and clock in at a cool 16 calories per cup. Use this cucumber to make healthy treats such as a cucumber salad with tomatoes and onions in a vinaigrette dressing, toss with fresh mozzarella, tomatoes, and a drizzle of balsamic vinegar, mix diced cucumbers with Greek yogurt, lemon, dill, and garlic for a refreshing tzatziki sauce for gyros or veggies, add to a crisp, fresh veggie salad, or thinly slice and add to a vinegar brine for quick pickles. Any way you slice, dice, or spiralize them, Cucumber is a refreshing, healthy addition to any meal."),
                               GroceryItem(itemName: "Lettuce", itemImage: "lettuce", itemInfo: "Make your salads wholesome and filling with the addition of Romaine Lettuce. This type of lettuce has extremely low-calorie content and high-water volume, and it's full of an impressive array of vitamins, minerals, and essential antioxidants, making it a nutritious addition to any meal! Create a fresh salad with cherry tomatoes, cucumbers, and garlic croutons, add some leaves to your smoothie, or use the structure of them for lettuce wraps. The options are endless when it comes to this versatile vegetable! Make sure you get your daily greens with Romaine Lettuce."),
                               GroceryItem(itemName: "Tomatoes", itemImage: "tomato", itemInfo: "Tomatoes are the leader when it comes to big, yummy, fresh tomatoes. The large size, juicy tomato taste and meaty texture make these tomatoes the perfect choice for slicing up and topping your favorite burger and sandwiches. Use them to make a hearty grilled cheese and tomato sandwich that's bursting with flavor. Slice some up and pair with fresh mozzarella, basil, and balsamic vinegar for a delicious appetizer. You can even enjoy a slice topped with a sprinkle of salt and pepper for a fresh, healthy snack. Add Tomatoes to your fresh produce basket today for a delicious juicy addition."),
                               ]
)

let section3 = GrocerySections(section: "Cereals",
                               items_Array: [
                               GroceryItem(itemName: "Cheerios", itemImage: "cheerios", itemInfo: "With the delicious flavor of golden honey,  Honey Nut Cheerios Heart Healthy Cereal makes your family’s breakfast hour that much sweeter. America’s favorite toasted honey Os are made with whole grain oats as the first ingredient. A drizzle of real honey and natural almond flavor creates un-bee-lievably delicious taste in every bowlful. Every serving provides 12 essential vitamins and minerals, and each little O is made simply with no artificial flavors or colors. Pour a bowlful of this heart healthy cereal for breakfast or put the box on the family table for everyone to enjoy."),
                               GroceryItem(itemName: "Cocoa Puffs", itemImage: "cocoa_puffs", itemInfo: "Your family will go cuckoo for the delicious chocolatey taste of Cocoa Puffs Cereal! Cocoa Puffs are naturally flavored frosted corn puffs bursting with the chocolatey taste kids love.Cocoa Puffs are made with whole grains (14g whole grain per serving; at least 48g recommended daily) and without high fructose corn syrup.. Every serving of Cocoa Puffs has vitamins and minerals..When Cocoa Puffs splashes down into your bowl, it turns the milk into an extra slurp-a-licious and chocolatey treat!"),
                               GroceryItem(itemName: "Frosted Flakes", itemImage: "frosted_flakes", itemInfo: "Just like Tony the Tiger, your whole family can get even their busiest days going with Kellogg's Frosted Flakes ready-to-eat breakfast cereal. Thanks to the toasty, crunchy corn flakes sprinkled with sweet frosting, adults and kids experience a tasty and satisfying bowl every time. Each serving of this cereal is fat free and a good source of 8 vitamins and minerals. Plus, there are no artificial colors or flavors; enjoy a bowl of Kellogg's Frosted Flakes with your favorite dairy or nut milk."),
                               GroceryItem(itemName: "Lucky Charms", itemImage: "lucky_charms", itemInfo: "Make a magical start to the day with Lucky Charms Gluten Free Cereal with Marshmallows. A crunchy bowl of frosted toasted oat cereal and Lucky's magical marshmallows brings smiles to breakfast time. Share the magic with everyone in your family. Pour a bowl with milk for breakfast, or pack a bag of the whole grain cereal with marshmallows for a snack. The toasted oat cereal provides kids with 19 grams of whole grain per serving, plus 12 vitamins and minerals. The kids cereal is also a good source of calcium and vitamin D."),
                               GroceryItem(itemName: "Mini Wheats", itemImage: "mini_wheats", itemInfo: "Greet the day with Original Frosted Mini-Wheats, a wholesome, low-fat breakfast cereal that's built for big days. These bite-sized biscuits pack a hearty crunch with crispy layers of wheat made from 100% whole grain and frosted with irresistible sweetness in every bite. With 48 grams of whole grain per 60-gram serving, these tasty squares are not only delicious but are an excellent source of fiber; Each serving contains a good source of 7 vitamins and minerals to help fuel you for what's ahead. ")
                               ]
)

let sections = [section1, section2, section3]
